### ISSUE TITLE
1.14-0-dev does not respond on MQTT messages

### ISSUE THREAD

**Issue by henkiejan1** [mcspr/espurna-nightly-builder#7]
Hi,

With the latest version, the 1.14.0-dev does mqtt not work correctly. It looks like it not responded on MQTT messages from Domoticz. When i downgrade to 1.13.6-dev verything works well. This happen to all my Sonoff Touch, Sonoff S20 and neo-coolcam switches. The Sonoff T1 EU2 does completly nothing and looks like dead. Also no response on the serial port. But maybe was the reboot from the build the trigger for dying hardware to die...

Could you look at this?

Thank you! :)

**Comment by mcspr** [comment]
No idea about the T1, but Domoticz is broken, I even see the problem locally :) Can you build the firmware yourself? The issue is with the `if (id >= _dcz_relay_state.size())` lines, which need to be removed.

https://github.com/xoseperez/espurna/blob/9a5698b342d6357bdd42267eb30932df9ce30260/code/espurna/domoticz.ino#L41-L50
https://github.com/xoseperez/espurna/commit/9a5698b342d6357bdd42267eb30932df9ce30260 is the culprit

Note that this issue tracker is for nightly builder problems and not for the resulting firmware, please use https://github.com/xoseperez/espurna/issues in the future. I'll push the fix as soon as I understand wtf is happening with `std::vector<bool>`...

**Comment by henkiejan1** [comment]
Just want to say that the T1 is restored. When in started OTA upgrade it rebooted itself to early with a corrupted image. But restored with a serial connection. I close it again and should use the official Espurna github in the future.

**Comment by mcspr** [comment]
Have you used webui updater, manual curl `/upgrade` or the espota (Arduino ide)? Or was it not .bin file and something else?
